### PR TITLE
First version of pcb layout

### PR DESCRIPTION
**Pull request by wuehr1999**
generated first version of pcb layout using gates to connect automatical mode to manual mode

### CODE REVIEW

**Comment by generationmake** [comment]
Good morning, could you add some LEDs for debugging? I suggest one for each power rail and one for the enable signal of each channel.
Could you also add some big electrolytic capacitor on each power rail? Just in case.

**Comment by wuehr1999** [comment]
> Good morning, could you add some LEDs for debugging? I suggest one for each power rail and one for the enable signal of each channel.
> Could you also add some big electrolytic capacitor on each power rail? Just in case.

Hi, the capacitors and LEDs are added now. Also the symbol of the NE555 is up to date.

**Comment by generationmake** [comment]
Hi @wuehr1999 could you add some version information like 0.1 ass string label on the pcb.
And could you update your logic table with the 5th state? Thank you.

**Comment by wuehr1999** [comment]
Hi @generationmake. I currently added version numbers and updated the logic table. There is also a pausing mode for automatical reading now.

**Comment by wuehr1999** [comment]
Hi @generationmake I just added the LEDs for trigger enable pin. Everything should be ready now.

**Comment by generationmake** [comment]
review was done in person on July 2nd.

**Pull request merged**
